properties:
  line-separator: <newline>
  chat-prefix: '&7[&aNotes&7] '
  db-type: sqlite
  permission-default: op
  notify-by-default: false
  notes-per-page: 5
  date-format: "MM/dd/yy h:mm a"
  check-new-version: true
  async-db-queries: true
  confirm-player-joined: true
  auto-note-permission: false
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: AN_