properties:
  line-separator: <newline>
  chat-prefix: '&7[&aNotes&7] '
  db-type: mysql
  permission-default: false
  notify-by-default: false
  notes-per-page: 5
  date-format: "MM/dd/yy h:mm a"
mysql:
  hostname: localhost
  username: root
  password: 
  port: 3306
  database: minecraft
  prefix: AN_