properties:
  # the line separator used in messages
  line-separator: '<newline>'
  
  # prefix used in chat, can have color codes
  chat-prefix: '&a[Notes] - '
  
  # DB type to use: mysql
  db-type: 'mysql'
  
# MySQL login info.
mysql:
  hostname: localhost
  username: root
  password: ''
  port: 3306
  database: minecraft
  prefix: "AN_"
